# Generated by Django 4.2.4 on 2025-03-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cataluge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
