# Generated by Django 4.2.4 on 2025-03-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataluge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(blank=True, to='cataluge.option'),
        ),
    ]
